[package]
name = "dta2json"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
once_cell = "1.19"
gurpschgen-lib = { path = "../gurpschgen-lib" }
regex = "1.10.5"
fancy-regex = "0.13"
serde_json = "1.0"