[package]
name = "gurpschgen-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.10.5"
fancy-regex = "0.13"
once_cell = "1.19"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
